### ISSUE TITLE
Find by equal with populate

### ISSUE THREAD

**Issue by kauelima** [clubedaentrega/node-mongo-admin#4]
When I have a column populated with data from another object, I cannot use the "find by equal" command in the elements since the tool tries to find the populated string on the source element.

When I need to find elements I need to unpopulate and with that I loose the information wanted.

**Comment by sitegui** [comment]
Regression

**Comment by sitegui** [comment]
Fixing one thing breaks another. In fact, the populate feature must be redesigned...
