### ISSUE TITLE
Change header name when populate is used

### ISSUE THREAD

**Issue by zilioti** [clubedaentrega/node-mongo-admin#6]
When you populate some data, the header is still the old one. I think if we changed for populated, it would cause no mess.

**Comment by sitegui** [comment]
Sorry, but I did not get you idea right. You meant a way to know whether a field was populated or not?

**Comment by zilioti** [comment]
Something like this!

Imagine you have object A and B. A has a property that is related to B, like Bname. But in the view, you want to show B lastname property. So you populate Bname property of A with B lastname property. The header will still be Bname and will show B lastname. It would be grateful, if the header changed for B lastname (populated) and show B lastname. So you would know what you have populated in the field.

Did I make it clear?

**Comment by sitegui** [comment]
The current `populate` implementation is a mess :disappointed: 
Maybe we could focus on rewriting this altogether...

I'll close this issue for now, but I'll accept PR on this if you will
